// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0--rc2
// source: api/dispatcher/dispatcher.proto

package dispatcher

import (
	protocol "github.com/zhihanii/im-pusher/api/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receivers []uint64          `protobuf:"varint,1,rep,packed,name=receivers,proto3" json:"receivers,omitempty"`
	Message   *protocol.Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PushReq) Reset() {
	*x = PushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dispatcher_dispatcher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReq) ProtoMessage() {}

func (x *PushReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_dispatcher_dispatcher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReq.ProtoReflect.Descriptor instead.
func (*PushReq) Descriptor() ([]byte, []int) {
	return file_api_dispatcher_dispatcher_proto_rawDescGZIP(), []int{0}
}

func (x *PushReq) GetReceivers() []uint64 {
	if x != nil {
		return x.Receivers
	}
	return nil
}

func (x *PushReq) GetMessage() *protocol.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type PushReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseReply      *protocol.BaseReply `protobuf:"bytes,1,opt,name=base_reply,json=baseReply,proto3" json:"base_reply,omitempty"`
	OfflineMembers []uint64            `protobuf:"varint,2,rep,packed,name=offline_members,json=offlineMembers,proto3" json:"offline_members,omitempty"`
}

func (x *PushReply) Reset() {
	*x = PushReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dispatcher_dispatcher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReply) ProtoMessage() {}

func (x *PushReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dispatcher_dispatcher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReply.ProtoReflect.Descriptor instead.
func (*PushReply) Descriptor() ([]byte, []int) {
	return file_api_dispatcher_dispatcher_proto_rawDescGZIP(), []int{1}
}

func (x *PushReply) GetBaseReply() *protocol.BaseReply {
	if x != nil {
		return x.BaseReply
	}
	return nil
}

func (x *PushReply) GetOfflineMembers() []uint64 {
	if x != nil {
		return x.OfflineMembers
	}
	return nil
}

var File_api_dispatcher_dispatcher_proto protoreflect.FileDescriptor

var file_api_dispatcher_dispatcher_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72,
	0x2f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x1a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x07, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x73, 0x12,
	0x2f, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x6c, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x36, 0x0a,
	0x0a, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0e,
	0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x32, 0x4a,
	0x0a, 0x0a, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x04,
	0x50, 0x75, 0x73, 0x68, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x69, 0x68, 0x61, 0x6e, 0x69,
	0x69, 0x2f, 0x69, 0x6d, 0x2d, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x65, 0x72, 0x3b, 0x64, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_dispatcher_dispatcher_proto_rawDescOnce sync.Once
	file_api_dispatcher_dispatcher_proto_rawDescData = file_api_dispatcher_dispatcher_proto_rawDesc
)

func file_api_dispatcher_dispatcher_proto_rawDescGZIP() []byte {
	file_api_dispatcher_dispatcher_proto_rawDescOnce.Do(func() {
		file_api_dispatcher_dispatcher_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_dispatcher_dispatcher_proto_rawDescData)
	})
	return file_api_dispatcher_dispatcher_proto_rawDescData
}

var file_api_dispatcher_dispatcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_dispatcher_dispatcher_proto_goTypes = []interface{}{
	(*PushReq)(nil),            // 0: api.dispatcher.PushReq
	(*PushReply)(nil),          // 1: api.dispatcher.PushReply
	(*protocol.Message)(nil),   // 2: api.protocol.Message
	(*protocol.BaseReply)(nil), // 3: api.protocol.BaseReply
}
var file_api_dispatcher_dispatcher_proto_depIdxs = []int32{
	2, // 0: api.dispatcher.PushReq.message:type_name -> api.protocol.Message
	3, // 1: api.dispatcher.PushReply.base_reply:type_name -> api.protocol.BaseReply
	0, // 2: api.dispatcher.Dispatcher.Push:input_type -> api.dispatcher.PushReq
	1, // 3: api.dispatcher.Dispatcher.Push:output_type -> api.dispatcher.PushReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_dispatcher_dispatcher_proto_init() }
func file_api_dispatcher_dispatcher_proto_init() {
	if File_api_dispatcher_dispatcher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_dispatcher_dispatcher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dispatcher_dispatcher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_dispatcher_dispatcher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dispatcher_dispatcher_proto_goTypes,
		DependencyIndexes: file_api_dispatcher_dispatcher_proto_depIdxs,
		MessageInfos:      file_api_dispatcher_dispatcher_proto_msgTypes,
	}.Build()
	File_api_dispatcher_dispatcher_proto = out.File
	file_api_dispatcher_dispatcher_proto_rawDesc = nil
	file_api_dispatcher_dispatcher_proto_goTypes = nil
	file_api_dispatcher_dispatcher_proto_depIdxs = nil
}
