grpc:
  service-name: dispatcher-service
  network: tcp
  bind-address: 127.0.0.1
  bind-port: 8103
  weight: 10

insecure:
  bind-address: 127.0.0.1
  bind-port: 8203

etcd:
  endpoints: ["192.168.88.101:2379"]
  LeaseExpire: 15

kafka:
  brokers: ["192.168.88.101:19092", "192.168.88.101:29092", "192.168.88.101:39092"]

redis:
  host: 192.168.88.101
  port: 6379
  password: 123456

logger:
  level: info
  format: console
  enable-color: false
  output-paths: ["/opt/dispatcher/log/dispatcher.log"]
  name: dispatcher-logger
