grpc:
  service-name: logic-service
  network: tcp
  bind-address: 127.0.0.1
  bind-port: 8102
  weight: 10

insecure:
  bind-address: 127.0.0.1
  bind-port: 8202

etcd:
  endpoints: ["192.168.88.101:2379"]
  LeaseExpire: 15

mysql:
  host: 192.168.88.101
  port: 3306
  user: zhi
  password: 123456
  database: cloud
  params: charset=utf8mb4&parseTime=True&loc=Local

redis:
  host: 192.168.88.101
  port: 16379
  password: 123456

logger:
  level: info
  format: console
  enable-color: false
  output-paths: ["/opt/logic/log/logic.log"]
  name: logic-logger
